// @generated from core.tl, tg_api_subset.tl; do not edit.
//! Constructor prefixes emitted by the streaming `tl-prefix-gen` tool.

use crate::tl::ConstructorId;

/// TL constructor prefix for `resPQ`.
pub const RES_PQ: ConstructorId = ConstructorId::new(0x05162463);
/// TL constructor prefix for `rpc_result`.
pub const RPC_RESULT: ConstructorId = ConstructorId::new(0xf35c6d01);
/// TL constructor prefix for `rpc_error`.
pub const RPC_ERROR: ConstructorId = ConstructorId::new(0x2144ca19);
/// TL constructor prefix for `pong`.
pub const PONG: ConstructorId = ConstructorId::new(0x347773c5);
/// TL constructor prefix for `new_session_created`.
pub const NEW_SESSION_CREATED: ConstructorId = ConstructorId::new(0x9ec20908);
/// TL constructor prefix for `msg_container`.
pub const MSG_CONTAINER: ConstructorId = ConstructorId::new(0x73f1f8dc);
/// TL constructor prefix for `gzip_packed`.
pub const GZIP_PACKED: ConstructorId = ConstructorId::new(0x3072cfa1);
/// TL constructor prefix for `msgs_ack`.
pub const MSGS_ACK: ConstructorId = ConstructorId::new(0x62d6b459);
/// TL constructor prefix for `bad_msg_notification`.
pub const BAD_MSG_NOTIFICATION: ConstructorId = ConstructorId::new(0xa7eff811);
/// TL constructor prefix for `bad_server_salt`.
pub const BAD_SERVER_SALT: ConstructorId = ConstructorId::new(0xedab447b);
/// TL constructor prefix for `req_pq_multi`.
pub const REQ_PQ_MULTI: ConstructorId = ConstructorId::new(0xbe7e8ef1);
/// TL constructor prefix for `ping_delay_disconnect`.
pub const PING_DELAY_DISCONNECT: ConstructorId = ConstructorId::new(0xf3427b8c);
/// TL constructor prefix for `boolFalse`.
pub const BOOL_FALSE: ConstructorId = ConstructorId::new(0xbc799737);
/// TL constructor prefix for `boolTrue`.
pub const BOOL_TRUE: ConstructorId = ConstructorId::new(0x997275b5);
/// TL constructor prefix for `inputUserSelf`.
pub const INPUT_USER_SELF: ConstructorId = ConstructorId::new(0xf7c1b13f);
/// TL constructor prefix for `inputPeerSelf`.
pub const INPUT_PEER_SELF: ConstructorId = ConstructorId::new(0x7da07ec9);
/// TL constructor prefix for `inputPeerUser`.
pub const INPUT_PEER_USER: ConstructorId = ConstructorId::new(0xdde8a54c);
/// TL constructor prefix for `inputPeerChannel`.
pub const INPUT_PEER_CHANNEL: ConstructorId = ConstructorId::new(0x27bcbbfc);
/// TL constructor prefix for `inputCheckPasswordSRP`.
pub const INPUT_CHECK_PASSWORD_SRP: ConstructorId = ConstructorId::new(0xd27ff082);
/// TL constructor prefix for `codeSettings`.
pub const CODE_SETTINGS: ConstructorId = ConstructorId::new(0xad253d78);
/// TL constructor prefix for `auth.sentCode`.
pub const AUTH_SENT_CODE: ConstructorId = ConstructorId::new(0x5e002502);
/// TL constructor prefix for `auth.sentCodeSuccess`.
pub const AUTH_SENT_CODE_SUCCESS: ConstructorId = ConstructorId::new(0x2390fe44);
/// TL constructor prefix for `auth.sentCodePaymentRequired`.
pub const AUTH_SENT_CODE_PAYMENT_REQUIRED: ConstructorId = ConstructorId::new(0xf8827ebf);
/// TL constructor prefix for `auth.authorization`.
pub const AUTH_AUTHORIZATION: ConstructorId = ConstructorId::new(0x2ea2c0d4);
/// TL constructor prefix for `auth.authorizationSignUpRequired`.
pub const AUTH_AUTHORIZATION_SIGN_UP_REQUIRED: ConstructorId = ConstructorId::new(0x44747e9a);
/// TL constructor prefix for `auth.codeTypeSms`.
pub const AUTH_CODE_TYPE_SMS: ConstructorId = ConstructorId::new(0x72a3158c);
/// TL constructor prefix for `auth.codeTypeCall`.
pub const AUTH_CODE_TYPE_CALL: ConstructorId = ConstructorId::new(0x741cd3e3);
/// TL constructor prefix for `auth.codeTypeFlashCall`.
pub const AUTH_CODE_TYPE_FLASH_CALL: ConstructorId = ConstructorId::new(0x226ccefb);
/// TL constructor prefix for `auth.codeTypeMissedCall`.
pub const AUTH_CODE_TYPE_MISSED_CALL: ConstructorId = ConstructorId::new(0xd61ad6ee);
/// TL constructor prefix for `auth.codeTypeFragmentSms`.
pub const AUTH_CODE_TYPE_FRAGMENT_SMS: ConstructorId = ConstructorId::new(0x06ed998c);
/// TL constructor prefix for `auth.codeTypeFirebaseSms`.
pub const AUTH_CODE_TYPE_FIREBASE_SMS: ConstructorId = ConstructorId::new(0xeea6e3f5);
/// TL constructor prefix for `auth.sentCodeTypeApp`.
pub const AUTH_SENT_CODE_TYPE_APP: ConstructorId = ConstructorId::new(0x3dbb5986);
/// TL constructor prefix for `auth.sentCodeTypeSms`.
pub const AUTH_SENT_CODE_TYPE_SMS: ConstructorId = ConstructorId::new(0xc000bba2);
/// TL constructor prefix for `auth.sentCodeTypeCall`.
pub const AUTH_SENT_CODE_TYPE_CALL: ConstructorId = ConstructorId::new(0x5353e5a7);
/// TL constructor prefix for `auth.sentCodeTypeFlashCall`.
pub const AUTH_SENT_CODE_TYPE_FLASH_CALL: ConstructorId = ConstructorId::new(0xab03c6d9);
/// TL constructor prefix for `auth.sentCodeTypeMissedCall`.
pub const AUTH_SENT_CODE_TYPE_MISSED_CALL: ConstructorId = ConstructorId::new(0x82006484);
/// TL constructor prefix for `auth.sentCodeTypeEmailCode`.
pub const AUTH_SENT_CODE_TYPE_EMAIL_CODE: ConstructorId = ConstructorId::new(0xf450f59b);
/// TL constructor prefix for `auth.sentCodeTypeSetUpEmailRequired`.
pub const AUTH_SENT_CODE_TYPE_SET_UP_EMAIL_REQUIRED: ConstructorId = ConstructorId::new(0xa5491dea);
/// TL constructor prefix for `auth.sentCodeTypeFragmentSms`.
pub const AUTH_SENT_CODE_TYPE_FRAGMENT_SMS: ConstructorId = ConstructorId::new(0xd9565c39);
/// TL constructor prefix for `auth.sentCodeTypeFirebaseSms`.
pub const AUTH_SENT_CODE_TYPE_FIREBASE_SMS: ConstructorId = ConstructorId::new(0x009fd736);
/// TL constructor prefix for `auth.sentCodeTypeSmsWord`.
pub const AUTH_SENT_CODE_TYPE_SMS_WORD: ConstructorId = ConstructorId::new(0xa416ac81);
/// TL constructor prefix for `auth.sentCodeTypeSmsPhrase`.
pub const AUTH_SENT_CODE_TYPE_SMS_PHRASE: ConstructorId = ConstructorId::new(0xb37794af);
/// TL constructor prefix for `updates.state`.
pub const UPDATES_STATE: ConstructorId = ConstructorId::new(0xa56c2a3e);
/// TL constructor prefix for `invokeAfterMsg`.
pub const INVOKE_AFTER_MSG: ConstructorId = ConstructorId::new(0xcb9f372d);
/// TL constructor prefix for `initConnection`.
pub const INIT_CONNECTION: ConstructorId = ConstructorId::new(0xc1cd5ea9);
/// TL constructor prefix for `invokeWithLayer`.
pub const INVOKE_WITH_LAYER: ConstructorId = ConstructorId::new(0xda9b0d0d);
/// TL constructor prefix for `invokeWithoutUpdates`.
pub const INVOKE_WITHOUT_UPDATES: ConstructorId = ConstructorId::new(0xbf9459b7);
/// TL constructor prefix for `auth.sendCode`.
pub const AUTH_SEND_CODE: ConstructorId = ConstructorId::new(0xa677244f);
/// TL constructor prefix for `auth.signUp`.
pub const AUTH_SIGN_UP: ConstructorId = ConstructorId::new(0xaac7b717);
/// TL constructor prefix for `auth.signIn`.
pub const AUTH_SIGN_IN: ConstructorId = ConstructorId::new(0x8d52a951);
/// TL constructor prefix for `auth.logOut`.
pub const AUTH_LOG_OUT: ConstructorId = ConstructorId::new(0x3e72ba19);
/// TL constructor prefix for `auth.checkPassword`.
pub const AUTH_CHECK_PASSWORD: ConstructorId = ConstructorId::new(0xd18b4d16);
/// TL constructor prefix for `account.getPassword`.
pub const ACCOUNT_GET_PASSWORD: ConstructorId = ConstructorId::new(0x548a30f5);
/// TL constructor prefix for `users.getFullUser`.
pub const USERS_GET_FULL_USER: ConstructorId = ConstructorId::new(0xb60f5918);
/// TL constructor prefix for `messages.getHistory`.
pub const MESSAGES_GET_HISTORY: ConstructorId = ConstructorId::new(0x4423e6c5);
/// TL constructor prefix for `messages.sendMessage`.
pub const MESSAGES_SEND_MESSAGE: ConstructorId = ConstructorId::new(0xfef48f62);
/// TL constructor prefix for `updates.getState`.
pub const UPDATES_GET_STATE: ConstructorId = ConstructorId::new(0xedd4882a);
